/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_espace_nutri_i (void)
{
  GtkWidget *espace_nutri_i;
  GtkWidget *fixed1;
  GtkWidget *image1;
  GtkWidget *image20;
  GtkWidget *image21;
  GtkWidget *button_msr_i;
  GtkWidget *image22;
  GtkWidget *buttonshow_i;
  GtkWidget *buttonajout1_i;

  espace_nutri_i = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_nutri_i), _("espace nutritionniste"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (espace_nutri_i), fixed1);
  gtk_widget_set_size_request (fixed1, 1064, 656);

  image1 = create_pixmap (espace_nutri_i, "Espace Nutritionniste (1).png");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 0, 0);
  gtk_widget_set_size_request (image1, 1064, 168);

  image20 = create_pixmap (espace_nutri_i, "Ajouter un menu (3).png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed1), image20, 328, 240);
  gtk_widget_set_size_request (image20, 424, 96);

  image21 = create_pixmap (espace_nutri_i, "Ajouter un menu (2).png");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed1), image21, 328, 384);
  gtk_widget_set_size_request (image21, 424, 96);

  button_msr_i = gtk_button_new_with_mnemonic ("");
  gtk_widget_show (button_msr_i);
  gtk_fixed_put (GTK_FIXED (fixed1), button_msr_i, 328, 384);
  gtk_widget_set_size_request (button_msr_i, 424, 96);
  gtk_button_set_relief (GTK_BUTTON (button_msr_i), GTK_RELIEF_NONE);

  image22 = create_pixmap (espace_nutri_i, "Ajouter un menu (4).png");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed1), image22, 328, 520);
  gtk_widget_set_size_request (image22, 424, 96);

  buttonshow_i = gtk_button_new_with_mnemonic ("");
  gtk_widget_show (buttonshow_i);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonshow_i, 328, 520);
  gtk_widget_set_size_request (buttonshow_i, 424, 96);
  gtk_button_set_relief (GTK_BUTTON (buttonshow_i), GTK_RELIEF_NONE);

  buttonajout1_i = gtk_button_new_with_mnemonic ("");
  gtk_widget_show (buttonajout1_i);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonajout1_i, 328, 240);
  gtk_widget_set_size_request (buttonajout1_i, 424, 96);
  gtk_button_set_relief (GTK_BUTTON (buttonajout1_i), GTK_RELIEF_NONE);

  g_signal_connect ((gpointer) button_msr_i, "clicked",
                    G_CALLBACK (on_button_msr_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonshow_i, "clicked",
                    G_CALLBACK (on_buttonshow_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonajout1_i, "clicked",
                    G_CALLBACK (on_buttonajout1_i_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_nutri_i, espace_nutri_i, "espace_nutri_i");
  GLADE_HOOKUP_OBJECT (espace_nutri_i, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (espace_nutri_i, image1, "image1");
  GLADE_HOOKUP_OBJECT (espace_nutri_i, image20, "image20");
  GLADE_HOOKUP_OBJECT (espace_nutri_i, image21, "image21");
  GLADE_HOOKUP_OBJECT (espace_nutri_i, button_msr_i, "button_msr_i");
  GLADE_HOOKUP_OBJECT (espace_nutri_i, image22, "image22");
  GLADE_HOOKUP_OBJECT (espace_nutri_i, buttonshow_i, "buttonshow_i");
  GLADE_HOOKUP_OBJECT (espace_nutri_i, buttonajout1_i, "buttonajout1_i");

  return espace_nutri_i;
}

GtkWidget*
create_window_ajout_i (void)
{
  GtkWidget *window_ajout_i;
  GtkWidget *fixed2;
  GtkWidget *entrychef_i;
  GtkWidget *label7;
  GtkWidget *entryplat_i;
  GtkWidget *entrydate_i;
  GtkWidget *calendar1;
  GtkObject *spinbutton1_i_adj;
  GtkWidget *spinbutton1_i;
  GtkWidget *labelmode_i;
  GtkWidget *buttonadd_i;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image4;
  GtkWidget *label11;
  GtkWidget *labelnbp_i;
  GtkWidget *labelgr_i;
  GtkWidget *label6;
  GtkWidget *labeldate_i;
  GtkWidget *labelmenu_i;
  GtkWidget *checkbutton1_i;
  GtkWidget *checkbutton2_i;
  GtkWidget *buttonhome_i;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image19;
  GtkWidget *label36;
  GtkWidget *buttonafficher_i;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image5;
  GtkWidget *label13;
  GtkWidget *labelplat_i;
  GtkWidget *image3;
  GtkWidget *labelchef_i;
  GtkWidget *labelplatvide_i;
  GtkWidget *labelchefvide_i;
  GtkWidget *labeldatevide_i;
  GtkWidget *comboboxMenu_i;

  window_ajout_i = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_ajout_i), _("Ajouter menu"));
  gtk_window_set_default_size (GTK_WINDOW (window_ajout_i), 1064, 680);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window_ajout_i), fixed2);
  gtk_widget_set_size_request (fixed2, 1064, 656);

  entrychef_i = gtk_entry_new ();
  gtk_widget_show (entrychef_i);
  gtk_fixed_put (GTK_FIXED (fixed2), entrychef_i, 168, 232);
  gtk_widget_set_size_request (entrychef_i, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrychef_i), 8226);

  label7 = gtk_label_new ("");
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 80, 336);
  gtk_widget_set_size_request (label7, 41, 17);

  entryplat_i = gtk_entry_new ();
  gtk_widget_show (entryplat_i);
  gtk_fixed_put (GTK_FIXED (fixed2), entryplat_i, 176, 352);
  gtk_widget_set_size_request (entryplat_i, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryplat_i), 8226);

  entrydate_i = gtk_entry_new ();
  gtk_widget_show (entrydate_i);
  gtk_fixed_put (GTK_FIXED (fixed2), entrydate_i, 688, 232);
  gtk_widget_set_size_request (entrydate_i, 240, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrydate_i), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed2), calendar1, 864, 464);
  gtk_widget_set_size_request (calendar1, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton1_i_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1_i = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_i_adj), 1, 0);
  gtk_widget_show (spinbutton1_i);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1_i, 584, 440);
  gtk_widget_set_size_request (spinbutton1_i, 64, 24);

  labelmode_i = gtk_label_new ("");
  gtk_widget_show (labelmode_i);
  gtk_fixed_put (GTK_FIXED (fixed2), labelmode_i, 152, 528);
  gtk_widget_set_size_request (labelmode_i, 49, 17);

  buttonadd_i = gtk_button_new ();
  gtk_widget_show (buttonadd_i);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonadd_i, 336, 608);
  gtk_widget_set_size_request (buttonadd_i, 136, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonadd_i), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox2), image4, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("<b><span color='Black'>  Ajouter </span></b>"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox2), label11, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  labelnbp_i = gtk_label_new (_("<b><span color='Black'>  Nombre de personnes </span></b>"));
  gtk_widget_show (labelnbp_i);
  gtk_fixed_put (GTK_FIXED (fixed2), labelnbp_i, 376, 440);
  gtk_widget_set_size_request (labelnbp_i, 200, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelnbp_i), TRUE);

  labelgr_i = gtk_label_new (_("<b><span color='Black'>  Groupe : </span></b>"));
  gtk_widget_show (labelgr_i);
  gtk_fixed_put (GTK_FIXED (fixed2), labelgr_i, 64, 520);
  gtk_widget_set_size_request (labelgr_i, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelgr_i), TRUE);

  label6 = gtk_label_new (_("<b><span color='#925B2A'>  Ajouter un Menu  </span></b>"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 440, 176);
  gtk_widget_set_size_request (label6, 177, 33);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  labeldate_i = gtk_label_new (_("<b><span color='Black'>  Date  </span></b>"));
  gtk_widget_show (labeldate_i);
  gtk_fixed_put (GTK_FIXED (fixed2), labeldate_i, 616, 232);
  gtk_widget_set_size_request (labeldate_i, 72, 32);
  gtk_label_set_use_markup (GTK_LABEL (labeldate_i), TRUE);

  labelmenu_i = gtk_label_new (_("<b><span color='Black'>  Menu  </span></b>"));
  gtk_widget_show (labelmenu_i);
  gtk_fixed_put (GTK_FIXED (fixed2), labelmenu_i, 600, 352);
  gtk_widget_set_size_request (labelmenu_i, 96, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelmenu_i), TRUE);

  checkbutton1_i = gtk_check_button_new_with_mnemonic (_("Groupe A"));
  gtk_widget_show (checkbutton1_i);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton1_i, 208, 520);
  gtk_widget_set_size_request (checkbutton1_i, 118, 24);

  checkbutton2_i = gtk_check_button_new_with_mnemonic (_("Groupe B"));
  gtk_widget_show (checkbutton2_i);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton2_i, 368, 520);
  gtk_widget_set_size_request (checkbutton2_i, 118, 24);

  buttonhome_i = gtk_button_new ();
  gtk_widget_show (buttonhome_i);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonhome_i, 992, 176);
  gtk_widget_set_size_request (buttonhome_i, 56, 48);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonhome_i), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image19 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox12), image19, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox12), label36, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  buttonafficher_i = gtk_button_new ();
  gtk_widget_show (buttonafficher_i);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonafficher_i, 584, 608);
  gtk_widget_set_size_request (buttonafficher_i, 144, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonafficher_i), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image5 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox3), image5, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("<b><span color='Black'>  Afficher  </span></b>"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox3), label13, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  labelplat_i = gtk_label_new (_("<b><span color='Black'>  Plat  </span></b>"));
  gtk_widget_show (labelplat_i);
  gtk_fixed_put (GTK_FIXED (fixed2), labelplat_i, 48, 360);
  gtk_widget_set_size_request (labelplat_i, 96, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelplat_i), TRUE);

  image3 = create_pixmap (window_ajout_i, "Espace Nutritionniste (1).png");
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed2), image3, 0, 0);
  gtk_widget_set_size_request (image3, 1064, 168);

  labelchef_i = gtk_label_new (_("<b><span color='Black'>  Chef Cuisinier  </span></b>"));
  gtk_widget_show (labelchef_i);
  gtk_fixed_put (GTK_FIXED (fixed2), labelchef_i, 32, 232);
  gtk_widget_set_size_request (labelchef_i, 144, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelchef_i), TRUE);

  labelplatvide_i = gtk_label_new ("");
  gtk_widget_show (labelplatvide_i);
  gtk_fixed_put (GTK_FIXED (fixed2), labelplatvide_i, 176, 384);
  gtk_widget_set_size_request (labelplatvide_i, 216, 32);

  labelchefvide_i = gtk_label_new ("");
  gtk_widget_show (labelchefvide_i);
  gtk_fixed_put (GTK_FIXED (fixed2), labelchefvide_i, 168, 264);
  gtk_widget_set_size_request (labelchefvide_i, 224, 32);

  labeldatevide_i = gtk_label_new ("");
  gtk_widget_show (labeldatevide_i);
  gtk_fixed_put (GTK_FIXED (fixed2), labeldatevide_i, 688, 264);
  gtk_widget_set_size_request (labeldatevide_i, 240, 32);

  comboboxMenu_i = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxMenu_i);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxMenu_i, 688, 344);
  gtk_widget_set_size_request (comboboxMenu_i, 240, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxMenu_i), _("Petit_D\303\251jeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxMenu_i), _("D\303\251jeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxMenu_i), _("Diner"));

  g_signal_connect ((gpointer) buttonadd_i, "clicked",
                    G_CALLBACK (on_buttonadd_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1_i, "toggled",
                    G_CALLBACK (on_checkbutton1_i_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2_i, "toggled",
                    G_CALLBACK (on_checkbutton2_i_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonhome_i, "clicked",
                    G_CALLBACK (on_buttonhome_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonafficher_i, "clicked",
                    G_CALLBACK (on_buttonafficher_i_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_ajout_i, window_ajout_i, "window_ajout_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_ajout_i, entrychef_i, "entrychef_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, label7, "label7");
  GLADE_HOOKUP_OBJECT (window_ajout_i, entryplat_i, "entryplat_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, entrydate_i, "entrydate_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (window_ajout_i, spinbutton1_i, "spinbutton1_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, labelmode_i, "labelmode_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, buttonadd_i, "buttonadd_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_ajout_i, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_ajout_i, image4, "image4");
  GLADE_HOOKUP_OBJECT (window_ajout_i, label11, "label11");
  GLADE_HOOKUP_OBJECT (window_ajout_i, labelnbp_i, "labelnbp_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, labelgr_i, "labelgr_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, label6, "label6");
  GLADE_HOOKUP_OBJECT (window_ajout_i, labeldate_i, "labeldate_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, labelmenu_i, "labelmenu_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, checkbutton1_i, "checkbutton1_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, checkbutton2_i, "checkbutton2_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, buttonhome_i, "buttonhome_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window_ajout_i, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window_ajout_i, image19, "image19");
  GLADE_HOOKUP_OBJECT (window_ajout_i, label36, "label36");
  GLADE_HOOKUP_OBJECT (window_ajout_i, buttonafficher_i, "buttonafficher_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_ajout_i, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_ajout_i, image5, "image5");
  GLADE_HOOKUP_OBJECT (window_ajout_i, label13, "label13");
  GLADE_HOOKUP_OBJECT (window_ajout_i, labelplat_i, "labelplat_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, image3, "image3");
  GLADE_HOOKUP_OBJECT (window_ajout_i, labelchef_i, "labelchef_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, labelplatvide_i, "labelplatvide_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, labelchefvide_i, "labelchefvide_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, labeldatevide_i, "labeldatevide_i");
  GLADE_HOOKUP_OBJECT (window_ajout_i, comboboxMenu_i, "comboboxMenu_i");

  return window_ajout_i;
}

GtkWidget*
create_window_msr_i (void)
{
  GtkWidget *window_msr_i;
  GtkWidget *fixed3;
  GtkWidget *entryID;
  GtkWidget *entrychef1;
  GtkWidget *entryplat2;
  GtkWidget *entrydate2;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label25_i;
  GtkWidget *label14;
  GtkWidget *label19;
  GtkWidget *label18;
  GtkWidget *labelchefvide_i;
  GtkWidget *labeldatevide_i;
  GtkWidget *labelmenuvide_i;
  GtkWidget *label21;
  GtkWidget *label20;
  GtkWidget *labelplatvide_i;
  GtkWidget *labelid_i;
  GtkWidget *image6;
  GtkWidget *buttonchercher_i;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image7;
  GtkWidget *label15;
  GtkWidget *buttonafficher1_i;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image13;
  GtkWidget *label29;
  GtkWidget *buttondel_i;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label17;
  GtkWidget *buttonmodifier_i;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image8;
  GtkWidget *label16;
  GtkWidget *combobox2_i;

  window_msr_i = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_msr_i), _("Modifier/Supprimer/Rechercher"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window_msr_i), fixed3);
  gtk_widget_set_size_request (fixed3, 1064, 672);

  entryID = gtk_entry_new ();
  gtk_widget_show (entryID);
  gtk_fixed_put (GTK_FIXED (fixed3), entryID, 168, 192);
  gtk_widget_set_size_request (entryID, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryID), 8226);

  entrychef1 = gtk_entry_new ();
  gtk_widget_show (entrychef1);
  gtk_fixed_put (GTK_FIXED (fixed3), entrychef1, 96, 336);
  gtk_widget_set_size_request (entrychef1, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrychef1), 8226);

  entryplat2 = gtk_entry_new ();
  gtk_widget_show (entryplat2);
  gtk_fixed_put (GTK_FIXED (fixed3), entryplat2, 96, 480);
  gtk_widget_set_size_request (entryplat2, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryplat2), 8226);

  entrydate2 = gtk_entry_new ();
  gtk_widget_show (entrydate2);
  gtk_fixed_put (GTK_FIXED (fixed3), entrydate2, 656, 336);
  gtk_widget_set_size_request (entrydate2, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrydate2), 8226);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 560, 544);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  label25_i = gtk_label_new (_("<b><span color='Black'>  Nombre de personnes  </span></b>"));
  gtk_widget_show (label25_i);
  gtk_fixed_put (GTK_FIXED (fixed3), label25_i, 360, 544);
  gtk_widget_set_size_request (label25_i, 192, 24);
  gtk_label_set_use_markup (GTK_LABEL (label25_i), TRUE);

  label14 = gtk_label_new (_("<b><span color='Black'>  ID  </span></b>"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 112, 200);
  gtk_widget_set_size_request (label14, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label19 = gtk_label_new (_("<b><span color='Black'>  Plat </span></b>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 176, 432);
  gtk_widget_set_size_request (label19, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label18 = gtk_label_new (_("<b><span color='Black'>  Chef Cuisinier  </span></b>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 136, 280);
  gtk_widget_set_size_request (label18, 128, 24);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  labelchefvide_i = gtk_label_new ("");
  gtk_widget_show (labelchefvide_i);
  gtk_fixed_put (GTK_FIXED (fixed3), labelchefvide_i, 96, 304);
  gtk_widget_set_size_request (labelchefvide_i, 216, 32);

  labeldatevide_i = gtk_label_new ("");
  gtk_widget_show (labeldatevide_i);
  gtk_fixed_put (GTK_FIXED (fixed3), labeldatevide_i, 656, 304);
  gtk_widget_set_size_request (labeldatevide_i, 216, 32);

  labelmenuvide_i = gtk_label_new ("");
  gtk_widget_show (labelmenuvide_i);
  gtk_fixed_put (GTK_FIXED (fixed3), labelmenuvide_i, 664, 448);
  gtk_widget_set_size_request (labelmenuvide_i, 208, 32);

  label21 = gtk_label_new (_("<b><span color='Black'>  Menu </span></b>"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 744, 432);
  gtk_widget_set_size_request (label21, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  label20 = gtk_label_new (_("<b><span color='Black'>  Date</span></b>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 728, 288);
  gtk_widget_set_size_request (label20, 72, 16);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  labelplatvide_i = gtk_label_new ("");
  gtk_widget_show (labelplatvide_i);
  gtk_fixed_put (GTK_FIXED (fixed3), labelplatvide_i, 96, 448);
  gtk_widget_set_size_request (labelplatvide_i, 216, 32);

  labelid_i = gtk_label_new ("");
  gtk_widget_show (labelid_i);
  gtk_fixed_put (GTK_FIXED (fixed3), labelid_i, 168, 224);
  gtk_widget_set_size_request (labelid_i, 224, 32);

  image6 = create_pixmap (window_msr_i, "Espace Nutritionniste (1).png");
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed3), image6, 0, 0);
  gtk_widget_set_size_request (image6, 1064, 168);

  buttonchercher_i = gtk_button_new ();
  gtk_widget_show (buttonchercher_i);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonchercher_i, 424, 184);
  gtk_widget_set_size_request (buttonchercher_i, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonchercher_i), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox4), image7, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("<b><span color='Black'>  Chercher </span></b>"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox4), label15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  buttonafficher1_i = gtk_button_new ();
  gtk_widget_show (buttonafficher1_i);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonafficher1_i, 440, 616);
  gtk_widget_set_size_request (buttonafficher1_i, 160, 56);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonafficher1_i), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image13 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox9), image13, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("<b><span color='Black'>  Afficher  </span></b>"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox9), label29, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  buttondel_i = gtk_button_new ();
  gtk_widget_show (buttondel_i);
  gtk_fixed_put (GTK_FIXED (fixed3), buttondel_i, 728, 184);
  gtk_widget_set_size_request (buttondel_i, 128, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttondel_i), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("<b><span color='Black'>  Supprimer  </span></b>"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox6), label17, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  buttonmodifier_i = gtk_button_new ();
  gtk_widget_show (buttonmodifier_i);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonmodifier_i, 568, 184);
  gtk_widget_set_size_request (buttonmodifier_i, 120, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonmodifier_i), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image8 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox5), image8, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("<b><span color='Black'>  Modifier  </span></b>"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox5), label16, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  combobox2_i = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2_i);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox2_i, 664, 480);
  gtk_widget_set_size_request (combobox2_i, 208, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_i), _("Peti_D\303\251jeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_i), _("D\303\251jeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_i), _("Diner"));

  g_signal_connect ((gpointer) buttonchercher_i, "clicked",
                    G_CALLBACK (on_buttonchercher_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonafficher1_i, "clicked",
                    G_CALLBACK (on_buttonafficher1_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttondel_i, "clicked",
                    G_CALLBACK (on_buttondel_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifier_i, "clicked",
                    G_CALLBACK (on_buttonmodifier_i_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_msr_i, window_msr_i, "window_msr_i");
  GLADE_HOOKUP_OBJECT (window_msr_i, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window_msr_i, entryID, "entryID");
  GLADE_HOOKUP_OBJECT (window_msr_i, entrychef1, "entrychef1");
  GLADE_HOOKUP_OBJECT (window_msr_i, entryplat2, "entryplat2");
  GLADE_HOOKUP_OBJECT (window_msr_i, entrydate2, "entrydate2");
  GLADE_HOOKUP_OBJECT (window_msr_i, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window_msr_i, label25_i, "label25_i");
  GLADE_HOOKUP_OBJECT (window_msr_i, label14, "label14");
  GLADE_HOOKUP_OBJECT (window_msr_i, label19, "label19");
  GLADE_HOOKUP_OBJECT (window_msr_i, label18, "label18");
  GLADE_HOOKUP_OBJECT (window_msr_i, labelchefvide_i, "labelchefvide_i");
  GLADE_HOOKUP_OBJECT (window_msr_i, labeldatevide_i, "labeldatevide_i");
  GLADE_HOOKUP_OBJECT (window_msr_i, labelmenuvide_i, "labelmenuvide_i");
  GLADE_HOOKUP_OBJECT (window_msr_i, label21, "label21");
  GLADE_HOOKUP_OBJECT (window_msr_i, label20, "label20");
  GLADE_HOOKUP_OBJECT (window_msr_i, labelplatvide_i, "labelplatvide_i");
  GLADE_HOOKUP_OBJECT (window_msr_i, labelid_i, "labelid_i");
  GLADE_HOOKUP_OBJECT (window_msr_i, image6, "image6");
  GLADE_HOOKUP_OBJECT (window_msr_i, buttonchercher_i, "buttonchercher_i");
  GLADE_HOOKUP_OBJECT (window_msr_i, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_msr_i, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_msr_i, image7, "image7");
  GLADE_HOOKUP_OBJECT (window_msr_i, label15, "label15");
  GLADE_HOOKUP_OBJECT (window_msr_i, buttonafficher1_i, "buttonafficher1_i");
  GLADE_HOOKUP_OBJECT (window_msr_i, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window_msr_i, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window_msr_i, image13, "image13");
  GLADE_HOOKUP_OBJECT (window_msr_i, label29, "label29");
  GLADE_HOOKUP_OBJECT (window_msr_i, buttondel_i, "buttondel_i");
  GLADE_HOOKUP_OBJECT (window_msr_i, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window_msr_i, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window_msr_i, image9, "image9");
  GLADE_HOOKUP_OBJECT (window_msr_i, label17, "label17");
  GLADE_HOOKUP_OBJECT (window_msr_i, buttonmodifier_i, "buttonmodifier_i");
  GLADE_HOOKUP_OBJECT (window_msr_i, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_msr_i, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window_msr_i, image8, "image8");
  GLADE_HOOKUP_OBJECT (window_msr_i, label16, "label16");
  GLADE_HOOKUP_OBJECT (window_msr_i, combobox2_i, "combobox2_i");

  return window_msr_i;
}

GtkWidget*
create_window_affich_i (void)
{
  GtkWidget *window_affich_i;
  GtkWidget *fixed4;
  GtkWidget *scrolledwindow_i;
  GtkWidget *treeview_i;
  GtkWidget *buttonfb_i;
  GtkWidget *image15;
  GtkWidget *button_insta_i;
  GtkWidget *image16;
  GtkWidget *button_yout_i;
  GtkWidget *image17;
  GtkWidget *image10;
  GtkWidget *buttonaccueil_i;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image14;
  GtkWidget *label34;
  GtkWidget *buttonsutree_i;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *label28;
  GtkWidget *buttontreemod_i;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image11;
  GtkWidget *label27;

  window_affich_i = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_affich_i), _("Afficher"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window_affich_i), fixed4);
  gtk_widget_set_size_request (fixed4, 1064, 672);

  scrolledwindow_i = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_i);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow_i, 24, 232);
  gtk_widget_set_size_request (scrolledwindow_i, 744, 440);

  treeview_i = gtk_tree_view_new ();
  gtk_widget_show (treeview_i);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_i), treeview_i);

  buttonfb_i = gtk_button_new ();
  gtk_widget_show (buttonfb_i);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonfb_i, 712, 192);
  gtk_widget_set_size_request (buttonfb_i, 48, 37);

  image15 = create_pixmap (window_affich_i, "button-facebookfinal.svg");
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (buttonfb_i), image15);

  button_insta_i = gtk_button_new ();
  gtk_widget_show (button_insta_i);
  gtk_fixed_put (GTK_FIXED (fixed4), button_insta_i, 656, 192);
  gtk_widget_set_size_request (button_insta_i, 48, 37);

  image16 = create_pixmap (window_affich_i, "aaaaaaaaaaa.png");
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (button_insta_i), image16);

  button_yout_i = gtk_button_new ();
  gtk_widget_show (button_yout_i);
  gtk_fixed_put (GTK_FIXED (fixed4), button_yout_i, 600, 192);
  gtk_widget_set_size_request (button_yout_i, 48, 37);

  image17 = create_pixmap (window_affich_i, "youtube.png");
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (button_yout_i), image17);

  image10 = create_pixmap (window_affich_i, "Espace Nutritionniste (1).png");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed4), image10, 0, 0);
  gtk_widget_set_size_request (image10, 1064, 168);

  buttonaccueil_i = gtk_button_new ();
  gtk_widget_show (buttonaccueil_i);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonaccueil_i, 1000, 176);
  gtk_widget_set_size_request (buttonaccueil_i, 56, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonaccueil_i), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image14 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox10), image14, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox10), label34, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  buttonsutree_i = gtk_button_new ();
  gtk_widget_show (buttonsutree_i);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonsutree_i, 832, 424);
  gtk_widget_set_size_request (buttonsutree_i, 152, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonsutree_i), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("<b><span color='Black'>  Supprimer  </span></b>"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox8), label28, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  buttontreemod_i = gtk_button_new ();
  gtk_widget_show (buttontreemod_i);
  gtk_fixed_put (GTK_FIXED (fixed4), buttontreemod_i, 832, 344);
  gtk_widget_set_size_request (buttontreemod_i, 152, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttontreemod_i), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox7), image11, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("<b><span color='Black'>  Modifier  </span></b>"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox7), label27, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  g_signal_connect ((gpointer) buttonfb_i, "clicked",
                    G_CALLBACK (on_buttonfb_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_insta_i, "clicked",
                    G_CALLBACK (on_button_insta_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_yout_i, "clicked",
                    G_CALLBACK (on_button_yout_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonaccueil_i, "clicked",
                    G_CALLBACK (on_button_acc_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsutree_i, "clicked",
                    G_CALLBACK (on_buttonsutree_i_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttontreemod_i, "clicked",
                    G_CALLBACK (on_buttontreemod_i_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_affich_i, window_affich_i, "window_affich_i");
  GLADE_HOOKUP_OBJECT (window_affich_i, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window_affich_i, scrolledwindow_i, "scrolledwindow_i");
  GLADE_HOOKUP_OBJECT (window_affich_i, treeview_i, "treeview_i");
  GLADE_HOOKUP_OBJECT (window_affich_i, buttonfb_i, "buttonfb_i");
  GLADE_HOOKUP_OBJECT (window_affich_i, image15, "image15");
  GLADE_HOOKUP_OBJECT (window_affich_i, button_insta_i, "button_insta_i");
  GLADE_HOOKUP_OBJECT (window_affich_i, image16, "image16");
  GLADE_HOOKUP_OBJECT (window_affich_i, button_yout_i, "button_yout_i");
  GLADE_HOOKUP_OBJECT (window_affich_i, image17, "image17");
  GLADE_HOOKUP_OBJECT (window_affich_i, image10, "image10");
  GLADE_HOOKUP_OBJECT (window_affich_i, buttonaccueil_i, "buttonaccueil_i");
  GLADE_HOOKUP_OBJECT (window_affich_i, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window_affich_i, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window_affich_i, image14, "image14");
  GLADE_HOOKUP_OBJECT (window_affich_i, label34, "label34");
  GLADE_HOOKUP_OBJECT (window_affich_i, buttonsutree_i, "buttonsutree_i");
  GLADE_HOOKUP_OBJECT (window_affich_i, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window_affich_i, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window_affich_i, image12, "image12");
  GLADE_HOOKUP_OBJECT (window_affich_i, label28, "label28");
  GLADE_HOOKUP_OBJECT (window_affich_i, buttontreemod_i, "buttontreemod_i");
  GLADE_HOOKUP_OBJECT (window_affich_i, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window_affich_i, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window_affich_i, image11, "image11");
  GLADE_HOOKUP_OBJECT (window_affich_i, label27, "label27");

  return window_affich_i;
}

GtkWidget*
create_window_valid_i (void)
{
  GtkWidget *window_valid_i;
  GtkWidget *fixed5;
  GtkWidget *radiobutton2_i;
  GSList *radiobutton2_i_group = NULL;
  GtkWidget *radiobutton1_i;
  GtkWidget *buttonok_i;
  GtkWidget *label33;

  window_valid_i = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_valid_i), _("Validation"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window_valid_i), fixed5);
  gtk_widget_set_size_request (fixed5, 416, 224);

  radiobutton2_i = gtk_radio_button_new_with_mnemonic (NULL, _("Oui"));
  gtk_widget_show (radiobutton2_i);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton2_i, 120, 128);
  gtk_widget_set_size_request (radiobutton2_i, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_i), radiobutton2_i_group);
  radiobutton2_i_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_i));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton2_i), TRUE);

  radiobutton1_i = gtk_radio_button_new_with_mnemonic (NULL, _("Non"));
  gtk_widget_show (radiobutton1_i);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton1_i, 296, 128);
  gtk_widget_set_size_request (radiobutton1_i, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_i), radiobutton2_i_group);
  radiobutton2_i_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_i));

  buttonok_i = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (buttonok_i);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonok_i, 200, 192);
  gtk_widget_set_size_request (buttonok_i, 80, 32);

  label33 = gtk_label_new (_("<b><span color='Black'>  Voulez-vous vraiment supprimer ce menu ? </span></b>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 64, 56);
  gtk_widget_set_size_request (label33, 352, 40);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  g_signal_connect ((gpointer) radiobutton2_i, "toggled",
                    G_CALLBACK (on_radiobutton2_i_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_i, "toggled",
                    G_CALLBACK (on_radiobutton1_i_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonok_i, "clicked",
                    G_CALLBACK (on_buttonok_i_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_valid_i, window_valid_i, "window_valid_i");
  GLADE_HOOKUP_OBJECT (window_valid_i, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window_valid_i, radiobutton2_i, "radiobutton2_i");
  GLADE_HOOKUP_OBJECT (window_valid_i, radiobutton1_i, "radiobutton1_i");
  GLADE_HOOKUP_OBJECT (window_valid_i, buttonok_i, "buttonok_i");
  GLADE_HOOKUP_OBJECT (window_valid_i, label33, "label33");

  return window_valid_i;
}

