/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_espace_nutri_i (void);
GtkWidget* create_window_ajout_i (void);
GtkWidget* create_window_msr_i (void);
GtkWidget* create_window_affich_i (void);
GtkWidget* create_window_valid_i (void);
