/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *espace_nutri_i;
  GtkWidget *window_ajout_i;
  GtkWidget *window_msr_i;
  GtkWidget *window_affich_i;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory ("../pixmaps");
  add_pixmap_directory ("../photos");
  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  espace_nutri_i = create_espace_nutri_i ();
  gtk_widget_show (espace_nutri_i);
  /*window_ajout_i = create_window_ajout_i ();
  gtk_widget_show (window_ajout_i);
  window_msr_i = create_window_msr_i ();
  gtk_widget_show (window_msr_i);
  window_affich_i = create_window_affich_i ();
  gtk_widget_show (window_affich_i);*/

  gtk_main ();
  return 0;
}

